### ISSUE TITLE
QR query

### ISSUE THREAD

**Issue by heyabredda** [PonnamKarthik/QRCodeReaderFlutter#1]
Hey,
I like your QR code reader,
However I was wondering if there is any chance to add a navigation bar within the camera or any other widgets??
As whenever it starts, it goes to a new window, but I would like it to start from a fragment designed by me.
Thanks you!

**Comment by ponnamkarthik** [comment]
presently it is not possible

**Comment by heyabredda** [comment]
Thank you for your response.
Also if there is no option to add any widget on the frame, and I decide to run the app on IOS device, do you think any IOS device will have a back button to return to the home page by default??

Thank you
