### ISSUE TITLE
Configuration 'compile' in project ':qr_reader' is deprecated. Use 'implementation' instead.

### ISSUE THREAD

**Issue by ramonmata** [PonnamKarthik/QRCodeReaderFlutter#2]
When launching my flutter app in debug mode, I am getting this message

`Configuration 'compile' in project ':qr_reader' is deprecated. Use 'implementation' instead.`

I am using the example source code from QRCodeReaderFlutter/example/lib/main.dart, which works fine, it is only that message

regards

**Comment by ponnamkarthik** [comment]
fixed in v0.1.1
